Доверстать главную страницу
htmlacademy-adaptive/81008-pognali-21 pull request #11
Opened 2020-12-07 23:25 UTC by Artmolla

2020-12-08 21:02 UTC, kosovych requested changes

2020-12-08 21:02 UTC, kosovych commented on source/index.html
> +        <img src="img/background_map.png" alt="Наш адрес: ул. Большая Конюшенная, 19/8">
растяни по всей ширине страницы

2020-12-10 12:56 UTC, Artmolla commented on source/index.html
> +        <img src="img/background_map.png" alt="Наш адрес: ул. Большая Конюшенная, 19/8">
Добавил интерактивную карту

2020-12-10 12:56 UTC, Artmolla commented on source/index.html
> +  <header class="page-header">
.page-header--scroll

2020-12-10 12:56 UTC, Artmolla commented on source/index.html
>        <div class="menu__header">
1. page-header--menu-open для .page-header
2. menu__body--menu-open для .menu__body

2020-12-10 12:56 UTC, Artmolla commented on source/index.html
>  <body class="page-body">
Буду постепенно добавлять в рамках текущих трех заданий, интерактивность для иконок запланировал добавить, когда приступлю к заданиям раздела Адаптивная графика.

2020-12-10 12:57 UTC, Artmolla commented on source/index.html
Поправил на сколько это было возможно

2020-12-10 12:57 UTC, Artmolla commented on source/index.html
>  </head>
Исправил

2020-12-10 20:59 UTC, kosovych requested changes

2020-12-10 20:59 UTC, kosovych commented on source/sass/contact-list.scss
> +}
не верно
1. Полупрозрачной становится вся кнопка, а должна только иконка
2. Сам круг нужно на css сделать а для самой иконки использовать SVG
3. Селекторы состояний (:active, :hover и тд) нужно строить от интерактивного элемента
`.link: .icon { color: red }`

2020-12-10 20:59 UTC, kosovych commented on source/index.html
>  </head>
![image](https://user-images.githubusercontent.com/19348382/101828194-e4a31600-3b39-11eb-8340-2a6ac1f21a32.png)

2020-12-10 20:59 UTC, kosovych commented on source/index.html
>  </head>
![image](https://user-images.githubusercontent.com/19348382/101828290-02707b00-3b3a-11eb-9e26-75e332ca0d4f.png)

2020-12-10 20:59 UTC, kosovych commented on source/index.html
>  </head>
![image](https://user-images.githubusercontent.com/19348382/101828366-1a47ff00-3b3a-11eb-8003-42fea483fcb7.png)

2020-12-10 20:59 UTC, kosovych commented on source/index.html
>  </head>
![image](https://user-images.githubusercontent.com/19348382/101828513-52e7d880-3b3a-11eb-9fd7-30938b6271d1.png)

2020-12-10 20:59 UTC, kosovych commented on source/index.html
>  </head>
![image](https://user-images.githubusercontent.com/19348382/101828587-6f841080-3b3a-11eb-8ed9-3f4199c334e7.png)

2020-12-10 20:59 UTC, kosovych commented on source/index.html
>  </head>
![image](https://user-images.githubusercontent.com/19348382/101828660-86c2fe00-3b3a-11eb-8a28-15ac312d9124.png)

2020-12-10 21:15 UTC, kosovych requested changes
1. Для иконочных кнопок круг сделай через CSS
2. Не используй для одних и тех же SVG picture с одними и теми же картинками. (в SVG буква S - scalable - масштабируемая)
3. Селекторы для интерактивности трой от интерактивного элемента
4. Добавь интерактивности элементам

2020-12-10 21:15 UTC, kosovych commented on source/index.html
> +              </picture>
Здесь должна быть только иконка, и только одна, SVG отлично масштабируется. Сам круг делается с помощью css

2020-12-10 21:15 UTC, kosovych commented on source/sass/button.scss
> +    opacity: 0.3;
не верно, вся кнопка не должна быть полупрозрачной

2020-12-10 21:15 UTC, kosovych commented on source/index.html
>              <a class="social-list__link link-reset" href="#">
добавь интерактивность

2020-12-10 21:15 UTC, kosovych commented on source/index.html
>          </a>
1. Это все ссылка (посмотри стайлгайд)
2. Добавь интерактивности

2020-12-10 21:15 UTC, kosovych commented on source/index.html
> +        <span class="button__arrow">&#9654;</span>
лучше SVG

2020-12-10 21:15 UTC, kosovych commented on source/index.html
> +            </picture>
зачем делать picture для одних и тех же картинок?

2020-12-10 21:25 UTC, kosovych requested changes

2020-12-10 21:25 UTC, kosovych commented on source/index.html
> +              <img src="img/flags/flag-thailand-35-24.png" alt="Флаг Таиланда">
эти картинки точно разные?

2020-12-10 21:25 UTC, kosovych commented on source/sass/register-form.scss
>  .register-form__input {
добавь интерактивность

2020-12-10 21:25 UTC, kosovych commented on source/index.html
> +          href="#">авторизуйтесь.</a>
добавь interested__button интерактивности

2020-12-10 21:25 UTC, kosovych commented on source/index.html
> +        </picture>
опять одинаковые картинки?

2020-12-13 16:07 UTC, merged