Module5 task2
htmlacademy-adaptive/81008-pognali-21 pull request #12
Opened 2020-12-17 13:20 UTC by Artmolla

2020-12-17 21:05 UTC, kosovych requested changes

2020-12-17 21:05 UTC, kosovych commented on source/form.html
>  <body class="page-body">
![image](https://user-images.githubusercontent.com/19348382/102543200-9eaafc80-40bb-11eb-84bf-e60c7cea7421.png)

2020-12-18 14:02 UTC, Artmolla commented on source/sass/profile.scss
> +  letter-spacing: -2.5px;
Проверил, исправил, спасибо.

2020-12-18 14:03 UTC, Artmolla commented on source/form.html
>  <body class="page-body">
Изменил расчет положения этих элементов

2020-12-18 18:22 UTC, merged