Module2 task3
htmlacademy-adaptive/81008-pognali-21 pull request #4
Opened 2020-11-15 23:24 UTC by Artmolla

2020-11-15 23:52 UTC, Artmolla commented
Hey, @kosovych could you please review my pull request. Add reviewers button appears inactive in my account. Probably only the repository owner can add reviewers. I've mentioned you in comments though, hope that helps.

2020-11-16 15:37 UTC, kosovych requested changes

2020-11-16 15:37 UTC, kosovych commented on source/catalog.html
> +      </table>
это разве табличные данные? как по мне это список спопок букв алфавита

2020-11-16 15:37 UTC, kosovych commented on source/catalog.html
> +        <fieldset class="companion-selection__content">
нет смысла в fieldset, который оборацивает всю форму. по идее у тебя их должно быть 5: хобби, музыка, еда, транспорт, левел

2020-11-16 15:37 UTC, kosovych commented on source/catalog.html
> +            </ul>
здесь не элменты формы, ибо это не для ввода информации пользователем, а для отображения существующей. разметь просто как список

2020-11-17 13:52 UTC, merged