Module3 task1
htmlacademy-adaptive/81008-pognali-21 pull request #5
Opened 2020-11-18 09:26 UTC by Artmolla

2020-11-18 19:41 UTC, kosovych reviewed
https://yoksel.github.io/html-tree/ проверь сдесь свой БЭМ и исправь пока еще не много сделал

2020-11-18 19:41 UTC, kosovych commented on source/sass/fonts.scss
> +}
не правильно подключил, ты не можешь все начертания подключить через одну директиву, нужно разделить по весу. например
```scss
@font-face {
  font-family: "Blogger Sans";
  src: url("../fonts/bloggersans.woff2") format("woff2"),
    url("../fonts/bloggersans.woff") format("woff");
}
@font-face {
  font-family: "Blogger Sans";
  font-weight: 700;
  src: 
    url("../fonts/bloggersans-bold.woff2") format("woff2"),
    url("../fonts/bloggersans-bold.woff") format("woff"),
}
```
и тд

2020-11-18 19:41 UTC, kosovych commented on source/sass/button.scss
> +.button--authorization {
проверь высоту

2020-11-18 19:41 UTC, kosovych commented on source/sass/user-card.scss
> +.user-card__user-status--offline {
в тег добавь и скрой доступно текстовый контент

2020-11-18 19:41 UTC, kosovych commented on source/sass/register-form.scss
> +.register-form__input {
стилизуй placeholder

2020-11-18 19:41 UTC, kosovych commented on source/sass/how-to-find.scss
> +.how-to-find__adress {
1. address
2. сбрось у адреса наклонный шрифт

2020-11-19 12:33 UTC, kosovych commented on source/sass/user-card.scss
> +.user-card__user-status--offline {
добавил статус пользователя, а какой статус? человек, который не видет цвет "кружка", не поймет

2020-11-19 12:33 UTC, kosovych commented on source/sass/button.scss
> +.button--authorization {
не исправлео

2020-11-19 12:36 UTC, kosovych requested changes

2020-11-19 12:36 UTC, kosovych commented on source/sass/variables.scss
> +$main-font: "Blogger Sans", "Tahoma", sans-serif;
у тебя изменилось название шрифта в директории `@font-face`, а здесь осталось старое

2020-11-19 13:22 UTC, Artmolla commented on source/sass/button.scss
> +.button--authorization {
Исправил, добавил модификатор для кнопки и сделал ее немного меньше, чем кнопка в меню, а также поправил ширину.

2020-11-19 13:22 UTC, Artmolla commented on source/sass/user-card.scss
> +.user-card__user-status--offline {
Добавил текс: 
1. "Статус пользователя: онлайн"
2. "Статус пользователя: офлайн"

2020-11-19 13:22 UTC, Artmolla commented on source/sass/variables.scss
> +$main-font: "Blogger Sans", "Tahoma", sans-serif;
исправил

2020-11-19 13:45 UTC, merged