Стилизация страницы каталога
htmlacademy-adaptive/81008-pognali-21 pull request #7
Opened 2020-11-22 16:27 UTC by Artmolla

2020-11-23 11:53 UTC, kosovych requested changes
- about__title directions__title companions__title имеют одинаковые стили, нужно вынести
- для текстовых блоков в 16px нужно удалить это свойство из CSS, ибо это свойство наследуемое

2020-11-23 11:53 UTC, kosovych commented on source/form.html
> +            <a class="pagination-list__link pagination__link--directions-plan" href="#"><span class="visually-hidden">slide-1</span></a>
почему ты описал все стили для "pagination-list__link" в модификаторе "pagination__link--directions-plan"?

2020-11-23 11:53 UTC, kosovych commented on source/form.html
> +            <a class="pagination__link pagination__link--directions-plan" href="#"><span class="visually-hidden">slide-3</span></a>
тоде самое

2020-11-23 11:53 UTC, kosovych commented on source/form.html
> +            <h3 class="alphabet__title">Выбирите страну</h3>
h2

2020-11-23 11:53 UTC, kosovych commented on source/sass/button.scss
> +
в .button и .button-reset дублируется font-family

2020-11-23 14:54 UTC, Artmolla commented on source/form.html
> +            <a class="pagination-list__link pagination__link--directions-plan" href="#"><span class="visually-hidden">slide-1</span></a>
На странице каталога тоже есть пагинация, только по отфильтрованным юзер-карточкам, решил разделить их модификатором, так как и то, и то, по сути пагинация, разница только в размере и цвете активного элемента. Или лучше разделить?

2020-11-23 14:54 UTC, Artmolla commented on source/form.html
> +            <h3 class="alphabet__title">Выбирите страну</h3>
Поправил

2020-11-23 14:54 UTC, Artmolla commented on source/sass/button.scss
> +
Исправил, оставил только у .button

2020-11-24 09:27 UTC, kosovych commented on source/form.html
> +            <a class="pagination-list__link pagination__link--directions-plan" href="#"><span class="visually-hidden">slide-1</span></a>
@Artmolla 
1. У тебя здесь модификатор `pagination__link--directions-plan` без элемента соответствующего
2. Не вижу одинаковой пагинации

2020-11-24 12:16 UTC, Artmolla commented on source/form.html
> +            <a class="pagination-list__link pagination__link--directions-plan" href="#"><span class="visually-hidden">slide-1</span></a>
Переделал

2020-11-24 18:22 UTC, kosovych requested changes

2020-11-24 18:22 UTC, kosovych commented on source/catalog.html
> +          <li class="filtered__breadcrumb filtered__breadcrumb"><a class="filtered__link filtered__link--active link-reset" href="#">1</a>
`filtered__breadcrumb filtered__breadcrumb` ?)

2020-11-24 18:22 UTC, kosovych commented on source/catalog.html
> +          <li class="filtered__breadcrumb filtered__breadcrumb"><a class="filtered__link filtered__link--active link-reset" href="#">1</a>
не совсем это breadcrumb. 
![image](https://user-images.githubusercontent.com/19348382/100135421-49037b80-2e92-11eb-857b-02c216d6717c.png) вот breadcrumb, а это как раз пагинация

2020-11-24 21:45 UTC, merged